### ISSUE TITLE
login authetication

### ISSUE THREAD

**Issue by DestroyerAlpha** [harshraj22/contest#19]
Need an auth.php to verify login and open up user dashboard. 
Try adding an [SQL Injection](https://www.w3schools.com/sql/sql_injection.asp) check

**Comment by harshraj22** [comment]
So is it like, on trying to login from home page, auth.php is called. If Credentials are correct, it is redirected to dashboard, else to home page ?

**Comment by DestroyerAlpha** [comment]
yes exactly

**Comment by abhiisshheekk** [comment]
I'm going to work on it

**Comment by abhiisshheekk** [comment]
we need to add table name and column names also in login.php, otherwise we would have to change them from auth.php everytime.

**Comment by DestroyerAlpha** [comment]
Agreed. Do the needful. I'll review the changes.

**Comment by abhiisshheekk** [comment]
Okay

**Comment by harshraj22** [comment]
- [ ]  Need a few comments ( at least one reference for sql injection in code ).
- [ ] Since we will have more tables,  we need to have more detailed name for table ( maybe something like $userAuthenticationTable
