### ISSUE TITLE
Add question upload page

### ISSUE THREAD

**Issue by harshraj22** [harshraj22/contest#34]
Add feature for admin to be able to upload questions.
- [ ] The authentication is checked ( anyone else trying to use the php page is forbidden : use $_SESSION ).
- [ ] Make All fields mendatory (time for question, title, etc ).
- [ ] Verify the same question code doesn't exists (use sql query )
- [ ] Update the questions , testcases directory.
- [ ] A separate table for the question is created.
   -  Table includes links to all submissions, their status (AC/WA/TLE etc ), time taken to run, time of running, etc

**Comment by JanhaviDadhania** [comment]
I will take this up
